apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
data:
  application.yml: |
    spring:
      kafka:
        bootstrap-servers: kafka-broker-1:29092,kafka-broker-2:29093
  api-gateway.yml: |
    server:
      port: 8080
  hello-service.yml: |-
    server:
      port: 8080
    greeting: "Hello from Config Server!"
  inventory-service.yml: |-
    spring:
      datasource:
        url: jdbc:postgresql://host.docker.internal:5432/shopcloud
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
      kafka:
        bootstrap-servers: kafka-broker-1:29092,kafka-broker-2:29093
    logging:
      level:
        org.apache.kafka.clients.consumer: DEBUG
        org.springframework.kafka: DEBUG
  user-service.yml: |-
    server:
      port: 8080
    logging:
      level:
        root: INFO