apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
data:
  application.yml: |
    {}
  api-gateway.yml: |
    server:
      port: 8080
  hello-service.yml: |-
    server:
      port: 8080
    greeting: "Hello from Config Server!"