apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopcloud-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: "true"
spec:
  project: default
  source:
    repoURL: 'https://github.com/4arturas/shopcloud.git'
    targetRevision: HEAD
    path: argocd/base
    kustomize:
      images:
        - cloud-config-server=arturix/cloud-config-server:latest
        - cloud-hello-service=arturix/cloud-hello-service:latest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shopcloud
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true