apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-reviews-service
  labels:
    app: rating-reviews-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-reviews-service
  template:
    metadata:
      labels:
        app: rating-reviews-service
    spec:
      containers:
        - name: rating-reviews-service
          image: arturix/cloud-rating-reviews-service:b45e514da577f86a093190e907309750661f19ef
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8080"
            
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
