apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: nodered
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: arturix/node-red:latest
        ports:
        - containerPort: 1880
        volumeMounts:
        - name: nodered-storage
          mountPath: /data
      volumes:
      - name: nodered-storage
        persistentVolumeClaim:
          claimName: nodered-pvc
