spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8080"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**
            - id: user-service-api-docs
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - RewritePath=/v3/api-docs/user-service, /v3/api-docs
            - id: product-service-api-docs
              uri: lb://product-service
              predicates:
                - Path=/v3/api-docs/product-service
              filters:
                - RewritePath=/v3/api-docs/product-service, /v3/api-docs
            - id: order-service-api-docs
              uri: lb://order-service
              predicates:
                - Path=/v3/api-docs/order-service
              filters:
                - RewritePath=/v3/api-docs/order-service, /v3/api-docs
            - id: inventory-service-api-docs
              uri: lb://inventory-service
              predicates:
                - Path=/v3/api-docs/inventory-service
              filters:
                - RewritePath=/v3/api-docs/inventory-service, /v3/api-docs
            - id: notification-service-api-docs
              uri: lb://notification-service
              predicates:
                - Path=/v3/api-docs/notification-service
              filters:
                - RewritePath=/v3/api-docs/notification-service, /v3/api-docs
            - id: payment-service-api-docs
              uri: lb://payment-service
              predicates:
                - Path=/v3/api-docs/payment-service
              filters:
                - RewritePath=/v3/api-docs/payment-service, /v3/api-docs
            - id: rating-reviews-service-api-docs
              uri: lb://rating-reviews-service
              predicates:
                - Path=/v3/api-docs/rating-reviews-service
              filters:
                - RewritePath=/v3/api-docs/rating-reviews-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: /v3/api-docs/user-service
      - name: Product Service
        url: /v3/api-docs/product-service
      - name: Order Service
        url: /v3/api-docs/order-service
      - name: Inventory Service
        url: /v3/api-docs/inventory-service
      - name: Notification Service
        url: /v3/api-docs/notification-service
      - name: Payment Service
        url: /v3/api-docs/payment-service
      - name: Rating Reviews Service
        url: /v3/api-docs/rating-reviews-service
  api-docs:
    groups:
      enabled: true
    paths:
      - group: user-service
        paths: /api/users/**
      - group: product-service
        paths: /api/products/**
      - group: order-service
        paths: /api/orders/**
      - group: inventory-service
        paths: /api/inventory/**
      - group: hello-service
        paths: /api/hello/**
      - group: notification-service
        paths: /api/notifications/**
      - group: payment-service
        paths: /api/payments/**
      - group: rating-reviews-service
        paths: /api/ratings/**

server:
  port: 8080

