spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://config-server:8080"
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/shopcloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Liquibase will manage schema
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080


